# Generated by Django 3.0.7 on 2020-08-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='numeroElementosAgregado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='sexo',
        ),
        migrations.AddField(
            model_name='pedido',
            name='elementosAgregado',
            field=models.CharField(default='nada', max_length=600),
        ),
    ]
