# Generated by Django 3.0.7 on 2020-07-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_produto_quantidadedisponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tamanhosPossiveisAdulto',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanhosPossiveisCriança',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanhosPossiveis',
            field=models.CharField(default='', max_length=300),
        ),
    ]
