# Generated by Django 3.1.1 on 2020-09-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200814_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
