# Generated by Django 3.0.7 on 2020-07-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200718_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='publicoAlvo',
        ),
    ]
