# Generated by Django 3.1.1 on 2020-09-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200924_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='listProducts',
            field=models.ManyToManyField(to='blog.RequestedProduct'),
        ),
    ]
