# Generated by Django 3.1.1 on 2020-10-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200924_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeBeneficiario', models.CharField(max_length=100)),
                ('nomeTecnico', models.CharField(max_length=100)),
                ('cartaoCidadao', models.IntegerField(unique=True)),
                ('telefone', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cartaoCidadao',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='elementosAgregado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nomeBeneficiario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nomeTecnico',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='telefone',
        ),
        migrations.AddField(
            model_name='pedido',
            name='listPeople',
            field=models.ManyToManyField(related_name='people', to='blog.RequestedProduct'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='listProducts',
            field=models.ManyToManyField(related_name='products', to='blog.RequestedProduct'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanhosPossiveisAdulto',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanhosPossiveisCriança',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
