# Generated by Django 3.1.1 on 2020-10-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_pedido_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='confirmacaoNovoPedido',
        ),
    ]
