# Generated by Django 3.1.1 on 2020-10-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_pedido_confirmacaonovopedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='listPeople',
            field=models.ManyToManyField(related_name='people', to='blog.RequestedPerson'),
        ),
    ]
