# Generated by Django 3.1.1 on 2020-10-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201007_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='listPeople',
            field=models.ManyToManyField(blank=True, related_name='people', to='blog.RequestedPerson'),
        ),
        migrations.AlterField(
            model_name='requestedperson',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
