# Generated by Django 3.0.7 on 2020-10-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201007_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
