# Generated by Django 3.1.1 on 2020-10-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201020_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituicao',
            options={'verbose_name': 'Equipa', 'verbose_name_plural': 'Equipas'},
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
