# Generated by Django 3.1.1 on 2021-01-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201026_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedproduct',
            name='numPeople',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='areaGeografica',
            field=models.CharField(max_length=300, verbose_name='Área Geográfica'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='instituicao',
            field=models.CharField(max_length=100, verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='publicoAlvo',
            field=models.CharField(default='população sem abrigo', max_length=100, verbose_name='Publico Alvo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estadoPedido',
            field=models.CharField(choices=[['Recebido', 'Recebido'], ['Em preparação', 'Em preparação'], ['A aguardar stock', 'A aguardar stock'], ['Pronto a levantar', 'Pronto a levantar'], ['Recolhido', 'Recolhido']], default='Recebido', max_length=50, verbose_name='Estado do Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='listPeople',
            field=models.ManyToManyField(blank=True, related_name='people', to='blog.RequestedPerson', verbose_name='Lista de Pessoas'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='listProducts',
            field=models.ManyToManyField(related_name='products', to='blog.RequestedProduct', verbose_name='Lista de Produtos'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipoPedido',
            field=models.CharField(choices=[['Requisição interna', 'Requisição interna'], ['Individual', 'Individual'], ['Agregado', 'Agregado']], default='Individual', max_length=50, verbose_name='Tipo de Pedido'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidadeMaxima',
            field=models.IntegerField(verbose_name='Quantidade Maxima'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanhosPossiveis',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Tamanhos(não roupa)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanhosPossiveisAdulto',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tamanhos Adulto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanhosPossiveisCriança',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tamanhos Criança'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipoProduto',
            field=models.CharField(max_length=150, unique=True, verbose_name='Tipo de Produto'),
        ),
    ]
