# Generated by Django 3.1.1 on 2021-01-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210120_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='listPeople',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='listProducts',
        ),
        migrations.AddField(
            model_name='pedido',
            name='nomeTitular',
            field=models.ManyToManyField(blank=True, related_name='people', to='blog.RequestedPerson', verbose_name='Lista de Pessoas'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Nome Equipa'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numPeople',
            field=models.IntegerField(default=1, verbose_name='Número de Pessoas'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanhosPossiveis',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Tamanhos (Sem ser Roupa)'),
        ),
    ]
