# Generated by Django 3.1.1 on 2021-01-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210126_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ccBenefeciario',
            field=models.CharField(default=213, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='nomeBenefeciario',
            field=models.CharField(default='Ola', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='phoneBenefeciario',
            field=models.CharField(default=123123123, max_length=100),
            preserve_default=False,
        ),
    ]
