# Generated by Django 3.1.1 on 2021-01-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210126_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nomeTecnico',
            field=models.CharField(default='Bernardo', max_length=100),
            preserve_default=False,
        ),
    ]
