# Generated by Django 3.1.1 on 2021-01-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210126_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipoPedido',
            field=models.CharField(choices=[['Requisição interna', 'Requisição interna'], ['Individual', 'Agregado']], default='Individual', max_length=50, verbose_name='Tipo de Pedido'),
        ),
        migrations.AlterField(
            model_name='requestedperson',
            name='cartaoCidadao',
            field=models.IntegerField(),
        ),
    ]
